# Plugin versioning - centralized location
set(PLUGIN_VERSION_MAJOR 1)
set(PLUGIN_VERSION_MINOR 22)
set(PLUGIN_VERSION_PATCH 0)
set(PLUGIN_VERSION "${PLUGIN_VERSION_MAJOR}.${PLUGIN_VERSION_MINOR}.${PLUGIN_VERSION_PATCH}")
set(PLUGIN_NAME_VERSIONED "Qt MCP Plugin")
set(PLUGIN_JSON_FILE "Qt_MCP_Plugin.json")
